### ISSUE TITLE
Implement InputParser

### ISSUE THREAD

**Issue by xuwd11** [cs207group4/cs207-FinalProject#1]
TODO list:
1. implement get_reactions (done).
2. implement get_nu (done).
3. implement get_rate_coeff_params (done).
4. suggestions appreciated :)
5. add documentation and tests.

**Suggestions for the implementation of class RateCoeff:**
1. include a method taking `InputParser.rate_coeff_params` (or the element in `InputParser.rate_coeff_params`; see InputParser.ipynb for details), T, and R as input and returning the rate coefficient(s). 
2. include a closure taking `InputParser.rate_coeff_params` (or the element in `InputParser.rate_coeff_params`) as input and returning a method, which takes T and R as input and returns the rate coefficient(s) when called.

**Comment by zeruniverse** [comment]
@xuwd11 Your inputparser does not give back the concentration... (i.e. how much O2 are there...)

Currently I tested with [1,1,1,1,1,1], when you finished this part, you can replace the test array in `test_chemkin.ipynb`.

**Comment by xuwd11** [comment]
@zeruniverse It seems input file only contains the fundamental information about the reactions, which does NOT include reaction conditions (such as concentration and temperature). So I assume concentration is not parsed from input file; but I'll keep an eye on whether demo input file is going to be updated.

**Comment by dsondak** [comment]
You are correct.  The input file will not contain state information (i.e. concentration or temperature).  It is up to the user of your software to supply that.

**Comment by zeruniverse** [comment]
maybe we have different interpretation about the given xml… I think <react>
and <product> tags contains concentration while coeffs should be parsed
from equation. I realized you count them as the coeffs.

**Comment by zeruniverse** [comment]
@dsondak Thanks for the clarification!

**Comment by dsondak** [comment]
The `<react>` and `<product>` tags contain the stoichiometric coefficients.

**Comment by kimiamavon** [comment]
It looks like the unit I was assigned with xuwd11 is done (thanks for being so quick xuwd11!). I'm going to run some tests and make doctests unless anyone suggests otherwise.

**Comment by zeruniverse** [comment]
@dsondak Is it possible that the input file contains multiple `reactionData` or it's guaranteed that each `xml` only contains one reaction system?
