### ISSUE TITLE
InputParser.ipynb gives 3 reactions but only 2 in file?

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#10]
Hey guys, 

I'm looking to add some tests but I saw  InputParser.ipynb gives three reactions back. The xml file only has two listed.  Why is this?

The output is : 

[{'equation': 'H + O2 =] OH + O',
  'id': 'reaction01',
  'products': {'O': 1.0, 'OH': 1.0},
  'rateCoeffParams': {'A': 35200000000.0, 'E': 71400.0, 'type': 'Arrhenius'},
  'reactants': {'H': 1.0, 'O2': 1.0},
  'reversible': 'no',
  'type': 'Elementary'},
 {'equation': 'H2 + O =] OH + H',
  'id': 'reaction02',
  'products': {'H': 1.0, 'OH': 1.0},
  'rateCoeffParams': {'A': 0.0506,
   'E': 26300.0,
   'b': 2.7,
   'type': 'modifiedArrhenius'},
  'reactants': {'H2': 1.0, 'O': 1.0},
  'reversible': 'no',
  'type': 'Elementary'},
 {'equation': 'H2 + OH =] H2O + H',
  'id': 'reaction03',
  'products': {'H': 1.0, 'H2O': 1.0},
  'rateCoeffParams': {'k': 1000.0, 'type': 'Constant'},
  'reactants': {'H2': 1.0, 'OH': 1.0},
  'reversible': 'no',
  'type': 'Elementary'}]

And the xml file is: 
<?xml version="1.0"?>

<ctml>

    <phase>
        <speciesArray> H O OH H2 O2 </speciesArray>
    </phase>

    <reactionData id="test_mechanism">

        
        <reaction reversible="no" type="Elementary" id="reaction01">
            <equation>H + O2 [=] OH + O</equation>
            <rateCoeff>
                <Arrhenius>
                    <A units="m3/mol/s">3.52e+10</A>
                    <b>-0.7</b>
                    <E units="J/mol">7.14e+04</E>
                </Arrhenius>
            </rateCoeff>
            <reactants>H:1 O2:1</reactants>
            <products>OH:1 O:1</products>
        </reaction>

        
        <reaction reversible="no" type="Elementary" id="reaction02">
            <equation>H2 + O [=] OH + H</equation>
            <rateCoeff>
                <Arrhenius>
                    <A units="m3/mol/s">5.06e-2</A>
                    <b>2.7</b>
                    <E units="J/mol">2.63e+04</E>
                </Arrhenius>
            </rateCoeff>
            <reactants>H2:1 O:1</reactants>
            <products>OH:1 H:1</products>
        </reaction>

    </reactionData>

</ctml>
© 2017 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
API
Training
Shop
Blog
About

**Comment by kimiamavon** [comment]
None of them are reverse reactions

**Comment by zeruniverse** [comment]
Because it **has** three reactions.

https://github.com/cs207group4/cs207-FinalProject/blob/master/rxns.xml

**Comment by kimiamavon** [comment]
Thank you- I must have been calling an older rxns file
