### ISSUE TITLE
make validation of input more rigorous

### ISSUE THREAD

**Issue by j6626** [cs207group4/cs207-FinalProject#11]

**Comment by zeruniverse** [comment]
@j6626 coverage significantly drops after your last push

**Comment by j6626** [comment]
Yeah, I'll update the tests too to account for the additional code.

**Comment by zeruniverse** [comment]
rxns data shouldn't be put into chemkin class otherwise repr() will be super hard to implement...

**Comment by j6626** [comment]
I don't see what the difficulty is

**Comment by zeruniverse** [comment]
For repr you are supposed to construct an exactly same object. However,
since np.array is contained in the data, repr(np.array) will be array and
this gives you an error of array not defined. You could try it.

**Comment by zeruniverse** [comment]
And since we will merge all classes into one file. I don't know if it
causes problem if __main__ is in the middle of the chemkin.py. My
suggestion is not to write __main__

**Comment by j6626** [comment]
Hi Jeffrey,

That's for testing, and it works fine when it's merged into the file. I'll
take it out at the end. Please be patient.

Regards,

Jane

**Comment by j6626** [comment]
I added a couple of tests that are passing locally but not with Travis. I'm looking into why this is.

**Comment by zeruniverse** [comment]
I think it's because you didn't add the test xml into github repo.

**Comment by j6626** [comment]
Yeah, good call. Thanks!
