### ISSUE TITLE
Meet tomorrow to present

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#12]
Hi Guys, 

Code review is at 12 tomorrow. Let's meet at 11:45 outside of the class. 

Thank you, 
K

**Comment by zeruniverse** [comment]
I have midterm tmr and might come later.

**Comment by dsondak** [comment]
@zeruniverse:  Please be sure to arrive at least 10 minutes before your scheduled review time (see [Code Review Format](https://github.com/IACS-CS-207/cs207-F17/blob/master/project/milestone1_code_review.md).

As this is a team project, I would encourage you to arrive early enough to make sure everyone is on the same page before your demo.

D.Sondak

**Comment by zeruniverse** [comment]
I think I can arrive at 11:50am.

**Comment by dsondak** [comment]
Great!  Let me know if you need me to talk to your other prof.  Their midterm shouldn't be clashing with ours.
