### ISSUE TITLE
Pip install 

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#16]
https://marthall.github.io/blog/how-to-package-a-python-app/

@kmavon @j6626

**Comment by kimiamavon** [comment]
Review this document. Do we have everything listed?

https://packaging.python.org/tutorials/distributing-packages/

**Comment by zeruniverse** [comment]
@kimiamavon @j6626 @xuwd11 I successfully uploaded the pychemkin package onto pypi. You should be able to install it in your computer with the command

``` bash
pip install pychemkin
```

No need to download this repo :)
