### ISSUE TITLE
Write Model Document

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#2]
+ Introduction: Describe what problem the code is solving. You may borrow the Latex expressions from my lecture notes. Discuss in broad strokes what the purpose of the code is along with any features. Do not describe the details of the code yet.
+ Installation: Describe where the code can be found and downloaded. Tell the user how to run the test suite. We are not releasing this code as a package yet, but when we do that this section will include instructions how how to install the package.
+ Basic Usage and Examples: Provide a few examples on using your software in some common situations. You may want to show how the code works with a small set of reactions.

**Comment by j6626** [comment]
I switched over to a PDF generated with LaTeX because GitHub otherwise doesn't render math expressions well.
