### ISSUE TITLE
Test ODE solvers

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#22]
Are all of them useful? Are they accurate?

- ‘RK45’ (Explicit Runge-Kutta method of order 5(4)) 
- ‘RK23’ (Explicit Runge-Kutta method of order 3(2)) 
- ‘Radau’ (Implicit Runge-Kutta method of Radau IIA family of order 5.) 
- ‘BDF’ (Implicit method based on Backward Differentiation Formulas.) 
- ‘LSODA’ (Adams/BDF method with automatic stiffness detection and switching) 
- (source: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp).

**Comment by dsondak** [comment]
What do you mean by "accurate"?

They are all useful for different problems.  RK45 is fast with nice convergence but it will fail for very stiff problems (like many kinetics problems).  BDF methods are the standard kinetics solvers.  You could offer all of them and let the user choose.
