### ISSUE TITLE
Convert latex to markdown

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#24]
Markdown actually supports latex equations (although GitHub can't display it correctly).

We need a readme.MD for PyPI

**Comment by zeruniverse** [comment]
So I think it's easier just to convert usermanual to markdown.

**Comment by j6626** [comment]
Why does the full user manual need to be on PyPi? The examples I've seen
usually just have a short blurb. And then we can link to the full manual.

**Comment by j6626** [comment]
i.e. like this https://pypi.python.org/pypi/emcee/

**Comment by zeruniverse** [comment]
I mean, we can put the whole file there so we don’t write another doc. But
I can surely write a short README as well if you think it’s better

**Comment by j6626** [comment]
I think it will take a while to convert from LaTeX to Markdown, without
adding much to the usability.  I think it would make sense for the README
should be a brief overview and the manual should contain the full details.
Copying and pasting a few sentences from the full manual to make a short
README should be sufficient.
