### ISSUE TITLE
Make tests

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#25]
I finished the package structure (codes should be under /pychemkin). I've fixed all current tests under /tests and you can start writing tests for modules you implemented.

@xuwd11 I noticed the sqlite file is not consistent with the given one in homework. Seems you pull it down from NASA website which contains more elements. I don't know if this is a trouble.

**Comment by zeruniverse** [comment]
@xuwd11 currently I imported all classes. Please rewrite `cs207-FinalProject/pychemkin/__init__.py` to include only classes you want users to have access.

-- Change `from xxx import *` to `from xxx import yyy,yyy,yyy`.

By the way, `SQLBuilder.py` seems redundant and decreases the coverage a lot. If it's unnecessary, please remove it.

**Comment by j6626** [comment]
Just to be consistent I'll put in the homework xml file. I don't think it
really matters too much insofar as the homework file is a subset of the
NASA file.

**Comment by zeruniverse** [comment]
@j6626 Actually you should use the homework sqlite file. We don't read xml...

**Comment by xuwd11** [comment]
@zeruniverse I'll write tests for SQLBuilder.
@j6626 I think we can keep the current the version at the moment. We can ask David whether it is allowed to use this larger database.

**Comment by xuwd11** [comment]
@dsondak I used http://combustion.berkeley.edu/gri_mech/version30/files30/thermo30.dat instead of homework file, which is a subset of this file, to create SQL database. Is it allowed?

**Comment by dsondak** [comment]
Yes.  That is allowed.

**Comment by zeruniverse** [comment]
90% coverage achived
