### ISSUE TITLE
Review and Edit Model Doc 

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#31]
No longer have items as "proposed features" but fully integrated with edits/additional notes that changed since proposed.

**Comment by j6626** [comment]
@kimiamavon can we confirm what the link to the most up-to-date version is? There was a comment yesterday about migrating to a new document because the old version somehow got locked?

**Comment by zeruniverse** [comment]
@j6626 I put a read-only link in the GitHub repo since otherwise all people in the world will know the address. I've emailed the group about the editable address.
