### ISSUE TITLE
Configure coverall and travis.ci

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#4]

**Comment by j6626** [comment]
Did it when I opened the repository!

**Comment by zeruniverse** [comment]
I meant maybe we need to modify `.travis.yml`... I don't know...

**Comment by zeruniverse** [comment]
`setup.cfg` should be rewritten to cover new modules.

**Comment by zeruniverse** [comment]
Also related to commit 78328a5789598d5dd6fe6973ed53fb291cceadd0
