### ISSUE TITLE
Group meeting for milstone 1

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#7]
Based on emails, I suggest Sunday (Oct. 15) 10am-11am at the basement of NW building (the place for data science lab).

**Comment by xuwd11** [comment]
Can we meet later (say 10am) since I live in Brookline?

**Comment by zeruniverse** [comment]
@xuwd11 I'm OK with 10-11

**Comment by kimiamavon** [comment]
10 is great

**Comment by j6626** [comment]
I'm fine with 10

**Comment by xuwd11** [comment]
OK, let's do 10 am.

**Comment by j6626** [comment]
I'm not sure I have key card access on the weekend. Could someone give me
their phone number so I can call if I'm locked out?

**Comment by zeruniverse** [comment]
Oops, I didn't know an access is required for NW at weekend. I don't have
special access to that building either... Maybe we should go to MD instead?

**Comment by j6626** [comment]
MD is fine

**Comment by j6626** [comment]
Have we finalized a place to meet?

**Comment by zeruniverse** [comment]
I'm ok with md

**Comment by kimiamavon** [comment]
I have card access to both NW and MD so just in case: 954 494 1614

**Comment by kimiamavon** [comment]
@ MD
